name: 'markets_yields'
version: '1.0.0'
profile: 'markets_yields'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  markets_yields:
    stg:
      +materialized: ephemeral
    mart:
      +materialized: table
