name: markets

services:
    airflow:
        image: apache/airflow:3.1.8
        environment:
          PYTHONPATH: /project/airflow/src
        env_file:
          - .env
        user: ${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-0}
        group_add:
          - "${DOCKER_GID}"
        volumes:
            - ./airflow:/project/airflow
            - /var/run/docker.sock:/var/run/docker.sock
            #- ./datalake:/project/datalake
            - ./images:/images
            - ./.env:/project/.env
        ports:
            - "8080:8080"
        command: standalone

    pyspark:
        build:
          context: .
          dockerfile: images/pyspark/Dockerfile
        environment:
          PYTHONPATH: /project/src
        env_file:
          - .env
        volumes:
            - ./airflow:/project/airflow
            - /var/run/docker.sock:/var/run/docker.sock
            - ./datalake:/project/datalake
            - ./migrations:/project/migrations
            - ./src:/project/src
            - ${DOCKER_HOME_DIR:-./dev/home}:/home/airflow
        ports:
            - "7070:7070"
        stdin_open: true
        tty: true
        command: bash
        user: ${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-0}

    dbt:
        build:
          context: .
          dockerfile: images/dbt/Dockerfile
        env_file:
          - .env
        volumes:
            - ./dbt:/project/dbt
            - ${DOCKER_HOME_DIR:-./dev/home}:/home/airflow
        stdin_open: true
        tty: true
        command: bash
        user: ${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-0}
